name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pandas==2.3 openpyxl

      - name: Run ruff (show results in CI log)
        run: |
          echo "Running ruff..."
          # Do not fail the job on ruff findings so the workflow continues and result.json is generated.
          ruff . || true

      - name: Run analysis and generate result.json
        run: |
          python execute.py > result.json

      - name: Upload result.json for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: result.json

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
